disabled_rules: # rule identifiers to exclude from running

  - empty_count
  - cyclomatic_complexity
  - large_tuple
  - trailing_comma
  - trailing_whitespace
  - switch_case_alignment
  - closure_parameter_position

opt_in_rules: # some rules are only opt-in
  - empty_count
  - explicit_init
  - empty_string
  - force_unwrapping
  - toggle_bool
  # Find all the available rules by running:
  # swiftlint rules

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Flutter
  - Tests
  - Carthage
  - Pods
  - .build
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
  - unused_declaration
  - unused_import

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# rules that have both warning and error levels, can set just the warning level
# implicitly
force_unwrapping: error

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - url
    - key
    - cpf
    - evp
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)